version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: book-keeper-qdrant
    ports:
      - "6345:6333"  # REST API
      - "6346:6334"  # gRPC
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - book-keeper-network
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  book-keeper-network:
    driver: bridge 